name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
      - name: Display .NET Version
        run: dotnet --version
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-restore --verbosity normal
